#!/usr/bin/env bash
#
# fbla version 0.0.1
#
# Written in 2019 by Franco Masotti/frnmst <franco.masotti@live.com>
#
# To the extent possible under law, the author(s) have dedicated all 
# copyright and related and neighboring rights to this software to the public 
# domain worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along 
# with this software. If not, see 
# <http://creativecommons.org/publicdomain/zero/1.0/>. 
#

. ./fbla

test_assert_isinstance()
{
    assert_isinstance '' bool \
        || { assert_isinstance 'true'  '' \
        || { assert_isinstance ''  '' \
        || { assert_isinstance 'true' boo \
        || { assert_isinstance 'true' bool \
        && { assert_isinstance 'false' bool \
        && { assert_isinstance 'strue' bool \
        || { assert_isinstance 'strue' str \
        && { assert_isinstance 'true' str \
        && { assert_isinstance '' str \
        && { assert_isinstance 'strue bye' str \
        && { assert_isinstance '123' str \
        && { assert_isinstance '123' int \
        && { assert_isinstance '1 0' int \
        || { assert_isinstance '1 a' int \
        || { printf "%s\n" 'ok'; return 0; }; }; }; }; }; }; }; }; }; }; }; }; }; }; }
        printf "%s\n" 'assertion error' 2>&1; return 1;
}

test_assert_isinstance
